spring:
  application:
    name: IngTest
  datasource:
    url: jdbc:postgresql://localhost:5432/ing
    username: user
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.tool.schema: DEBUG
jwt:
  expiration: 86400000
  secret: zRa1Maxz94AgsKzKMkdt8kubj7SeMusWb6+wBGuCTFs=

#  security:
#    user:
#      name: admin
#      password: admin
#      roles: ADMIN